## Import Libraries

In [1]:
#import libraries
import nltk
import numpy as np
import tensorflow as tf
import random
import keras
import spacy 
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from nltk.stem.lancaster import LancasterStemmer
import json
from datetime import datetime,date


## Read the data

In [2]:
nltk.download('punkt')
stemmer =  LancasterStemmer()


[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [3]:

with open('../input/datajson/data.json') as file:
    data = json.load(file)

## processing on Data

In [4]:
words = []
labels = []
docs_x = []
docs_y = []

for intent in data['intents']:
    for pattern in intent['patterns']:
        #tokenize
        wrds = nltk.word_tokenize(pattern)
        words.extend(wrds)
        docs_x.append(wrds)
        docs_y.append(intent["tag"])

    if intent['tag'] not in labels:
        labels.append(intent['tag'])

In [5]:
print("doc_x" , docs_x)
print("--------------------------")
print("doc_y" , docs_y)
print("--------------------------")

print("words",words)
print("--------------------------")

print(labels)

doc_x [['Hi'], ['How', 'are', 'you'], ['Is', 'anyone', 'there', '?'], ['Hello'], ['Good', 'day'], ['Bye'], ['See', 'you', 'later'], ['Goodbye'], ['Thanks'], ['Thank', 'you'], ['That', "'s", 'helpful'], ['Emergency'], ['Police'], ['I', 'am', 'in', 'danger'], ['how', 'are', 'you', '?'], ['sup'], ['how', 'it', 'is', 'going', '?'], ['How', 'is', 'the', 'weather', '?'], ['tell', 'me', 'the', 'weather', 'forecast', 'now'], ['what', "'s", 'the', 'forecast', '?'], ['what', 'is', 'the', 'weather', 'like', 'right', 'now', '?'], ['what', "'s", 'the', 'temperature', 'going', 'to', 'be', 'tomorrow', '?'], ['Is', 'it', 'raining', '?'], ['What', 'is', 'the', 'Hotel', 'next', 'to', 'me', '?'], ['I', 'want', 'to', 'find', 'a', 'hotel'], ['I', 'need', 'to', 'sleep'], ['What', 'are', 'the', 'hotel', 'in', 'location'], ['tell', 'me', 'about', 'topic'], ['what', 'do', 'you', 'know', 'about', 'topic'], ['change', '50', 'dollars', 'to', 'pounds'], ['Convert', '50', 'Euro', 'to', 'pound'], ['Convert', '50', '

In [6]:

words = [stemmer.stem(w.lower()) for w in words if w != "?"]
#print(words)
words = sorted(list(set(words)))

labels = sorted(labels)

training = []
output = []

out_empty = [0 for _ in range(len(labels))]

In [7]:
print(words)

["'s", '50', 'a', 'about', 'am', 'anyon', 'ar', 'be', 'bye', 'chang', 'clin', 'convert', 'dang', 'day', 'do', 'doll', 'eat', 'emerg', 'euro', 'find', 'forecast', 'going', 'good', 'goodby', 'hello', 'help', 'hi', 'hotel', 'how', 'i', 'in', 'is', 'it', 'know', 'lat', 'lik', 'loc', 'me', 'medicin', 'nee', 'next', 'now', 'pol', 'pound', 'rain', 'resta', 'right', 'see', 'sleep', 'sup', 'tel', 'temp', 'thank', 'that', 'the', 'ther', 'to', 'tomorrow', 'top', 'want', 'weath', 'what', 'you']


In [8]:
for x, doc in enumerate(docs_x):
    bag = []

    wrds = [stemmer.stem(w.lower()) for w in doc]

    for w in words:
        if w in wrds:
            bag.append(1)
        else:
            bag.append(0)

    #print(bag)
    output_row = out_empty[:]
    output_row[labels.index(docs_y[x])] = 1
    #print(output_row)

    training.append(bag)
    output.append(output_row)

#print(training)
#print(len(training)) >>> 31
training = np.array(training)
output = np.array(output)

In [9]:
print("output",output)
print("--------------------------")
print("training",training)

output [[0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 

## Build Model

In [10]:
# Create model - 3 layers. First layer 128 neurons, second layer 64 neurons and 3rd output layer contains number of neurons
# equal to number of intents to predict output intent with softmax
model = Sequential()
model.add(Dense(128, input_shape=(len(training[0]),), activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(len(output[0]), activation='softmax'))


User settings:

   KMP_AFFINITY=granularity=fine,verbose,compact,1,0
   KMP_BLOCKTIME=0
   KMP_DUPLICATE_LIB_OK=True
   KMP_INIT_AT_FORK=FALSE
   KMP_SETTINGS=1
   KMP_WARNINGS=0

Effective settings:

   KMP_ABORT_DELAY=0
   KMP_ADAPTIVE_LOCK_PROPS='1,1024'
   KMP_ALIGN_ALLOC=64
   KMP_ALL_THREADPRIVATE=128
   KMP_ATOMIC_MODE=2
   KMP_BLOCKTIME=0
   KMP_CPUINFO_FILE: value is not defined
   KMP_DETERMINISTIC_REDUCTION=false
   KMP_DEVICE_THREAD_LIMIT=2147483647
   KMP_DISP_NUM_BUFFERS=7
   KMP_DUPLICATE_LIB_OK=true
   KMP_ENABLE_TASK_THROTTLING=true
   KMP_FORCE_REDUCTION: value is not defined
   KMP_FOREIGN_THREADS_THREADPRIVATE=true
   KMP_FORKJOIN_BARRIER='2,2'
   KMP_FORKJOIN_BARRIER_PATTERN='hyper,hyper'
   KMP_GTID_MODE=3
   KMP_HANDLE_SIGNALS=false
   KMP_HOT_TEAMS_MAX_LEVEL=1
   KMP_HOT_TEAMS_MODE=0
   KMP_INIT_AT_FORK=true
   KMP_LIBRARY=throughput
   KMP_LOCK_KIND=queuing
   KMP_MALLOC_POOL_INCR=1M
   KMP_NUM_LOCKS_IN_BLOCK=1
   KMP_PLAIN_BARRIER='2,2'
   KMP_PLAIN_BARRIER_P

In [11]:
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])


In [12]:
model.fit(training, output, epochs=200)


2022-03-17 16:35:56.632675: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/200
2/2 [==============================] - 1s 7ms/step - loss: 2.3890 - accuracy: 0.1000
Epoch 2/200
2/2 [==============================] - 0s 6ms/step - loss: 2.4664 - accuracy: 0.0750
Epoch 3/200
2/2 [==============================] - 0s 5ms/step - loss: 2.4236 - accuracy: 0.0250
Epoch 4/200
2/2 [==============================] - 0s 5ms/step - loss: 2.3896 - accuracy: 0.1250
Epoch 5/200
2/2 [==============================] - 0s 6ms/step - loss: 2.3892 - accuracy: 0.1000
Epoch 6/200
2/2 [==============================] - 0s 4ms/step - loss: 2.3526 - accuracy: 0.0750
Epoch 7/200
2/2 [==============================] - 0s 5ms/step - loss: 2.2666 - accuracy: 0.2750
Epoch 8/200
2/2 [==============================] - 0s 5ms/step - loss: 2.3237 - accuracy: 0.1250
Epoch 9/200
2/2 [==============================] - 0s 4ms/step - loss: 2.3028 - accuracy: 0.1250
Epoch 10/200
2/2 [==============================] - 0s 4ms/step - loss: 2.2383 - accuracy: 0.2250
Epoch 11/200
2/2 [===========

In [13]:
model.save("model.h5")
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)


# Space Entity

In [14]:
pip install spacy_langdetect

     |████████████████████████████████| 998 kB 708 kB/s            
  Preparing metadata (setup.py) ... - done
  Created wheel for langdetect: filename=langdetect-1.0.7-py3-none-any.whl size=993430 sha256=a48ff622c0973dd7a27c37a72d077efe422fcd3dafaf01afab0b22d34c5c26bb
  Stored in directory: /root/.cache/pip/wheels/89/79/3b/9885ae7f4308f73c514f96d8574d40d7d8173a27731b674013
Successfully built langdetect
Note: you may need to restart the kernel to use updated packages.


In [15]:
import spacy
from spacy.lang.en import English
from spacy.pipeline import EntityRuler
import json
from spacy_langdetect import LanguageDetector
from spacy.language import Language

In [16]:
def open_data(name):
  with open(name,'r') as f:
    data =  json.load(f)
  return data

In [17]:
def create_training_data(data):
  patternss = []
  for label in data: 
    for item in data[label]:
        pattern = {
                    "label": label,
                    "pattern": item
                    }
        patternss.append(pattern)

        pattern2 = {
                    "label": label,
                    "pattern": item.lower()
                    }
        
        patternss.append(pattern2)
  return (patternss)

In [18]:
def generate_model(patterns):
  nlp = English()
  ruler = nlp.add_pipe("entity_ruler")
  ruler.add_patterns(pattern)
  nlp.to_disk("visit_egypt")
  return nlp

In [19]:
def  test_model(model,text):
  doc = model(text)
  result = []
  for ent in doc.ents:
     result.append({"Name": ent.text , "Label": ent.label_})
  return result

In [20]:
data =  open_data('../input/datajson/data_space.json')

In [21]:
pattern =  create_training_data(data)

In [22]:
model  = generate_model(pattern)

In [23]:
model_entity = spacy.load('./visit_egypt')


In [24]:
result = test_model(model_entity,'what do you know about Ramesses')
result

[{'Name': 'Ramesses', 'Label': 'names'}]

## Test

In [25]:
def bag_of_words(s, words):
    bag = [0 for _ in range(len(words))]

    s_words = nltk.word_tokenize(s)
    s_words = [stemmer.stem(word.lower()) for word in s_words]

    for se in s_words:
        for i, w in enumerate(words):
            if w == se:
                bag[i] = 1
    return np.array(bag)



def net(word) :
     sentence = []
     for ent in nlp(word).ents:
        sentence.append({"Name": ent.text , "Label": ent.label_})
     return sentence


def chat():
    print("Start talking with the bot (type quit to stop)!")
    while True:
        inp = input("You: ")
        if inp.lower() == "quit":
            break
        
        x =  bag_of_words(inp, words)
        y =  net(inp) 
        results = model.predict(np.array([x]))
        results_index = np.argmax(results)
        tag = labels[results_index]
        if tag == "date":
               time()
        else:
         print(tag,results_index)
         for tg in data["intents"]:
                
            if tg['tag'] == tag:
                responses = tg['responses']

         print(random.choice(responses))

In [26]:
#chat()